#!/bin/bash

# This creates a new plugin based on micrositeComponentBoilerplate repo

############################
# usage:
# $ ./bootstrap pluginName 'description of the plugin'
#
# notes:
# plugin will be created off of parent directory
#
# requires:
# http://defunkt.io/hub/
############################

########## Variables
plugin=$1
description=$2

########## Script
echo "creating ${plugin} plugin..."
cd ..
git clone https://github.com/okize/micrositeComponentBoilerplate.git $plugin
cd $plugin
rm -rf ./.git
for file in `find . -name 'pluginName.*'`; do
  mv "$file" "${file/pluginName/$plugin}"
done
echo 'creating readme file'
echo $description > readme.md
for file in $(grep -r -l '{{@pluginName}}' ./*) ; do
  if [ $file != './bootstrap' ]; then
     sed "s/{{@pluginName}}/$plugin/g" $file > $file.$$ && mv $file.$$ $file
  fi
done
mv makefile.tmp makefile
make
rm bootstrap
git init
git add . && git commit -m 'initial commit'
hub create -d "${description}"
git push -u origin master